version: "3.6"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: es
    environment:
      - node.name=es
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - './es_data:/usr/share/elasticsearch/data'
    ports:
      - 9200:9200

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8085:8080
    volumes:
      - ./documentation:/documentation
    environment:
      SWAGGER_JSON: /documentation/swagger.json
      BASE_URL: /documentation/api/v1

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: database
      JWT_SECRET: "QgTPVshDVPqqcNMvinBd8vWhGJ8i7udr"
      DB_PASSWORD: "CvUuM6YK3YVveTYc2McSUvkSxRRkFEJn"
      DB_USER: "user"
      FRONT_URL: "http://localhost"
      DOCUMENTATION_URL: "http://localhost:8085"
      PORT: "8080"
    ports:
      - 8080:8080
